### ISSUE TITLE
Missing method in SpPharoJsClientSideApp

### ISSUE THREAD

**Issue by StephanEggermont** [ironirc/Spec-PharoJS#1]
#js_appendChild: seems to be missing in #appendStyleElementToHeadWith:

**Comment by ironirc** [comment]
This targets a javascript method on instances of `HTMLElement` in the browser. 
The `js_` prefix is a sort of PharoJS directive, and makes it transpile to `appendChild()`.
So, this code won't run in Smalltalk, only in Javascript.
